spring:
  application:
    name: api-user
  datasource:
    url: jdbc:mysql://192.168.60.94:3306/ksxt
    username: ksxt_admin
    password: Passw0rd!
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  redis:
    host: 192.168.60.92
    timeout: 3000
    expire: 1800
    password:
    port: 6379
    database: 5
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制)
        min-idle: 0 # 连接池中的最小空闲连接
mybatis:
  mapper-locations: classpath:mapper/*.xml
###配置打印sql //包路径为mapper文件包路径
logging:
  level:
    com.sbs.provider.dao: debug
  config: classpath:logback-spring.xml
  path: D:/nmyslog/user
session:
  redis:
    expireTime: 3600
